<a href="https://colab.research.google.com/github/alra-code/Portifolio_python/blob/main/An%C3%A1lise_de_dados_com_python_modulo_2_(Vari%C3%A2ncia_e_desvio_padr%C3%A3o)_Tic_em_Trilhas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Compreendendo Variância e Desvio Padrão

In [ ]:
import statistics as st
lista1=[0,1,2,3,3,3,4,4,4,5,5,6]
lista2=[0,-1,-2,30,3,3,4,40,4,-50,5,6]

print(st.mean(lista1))
print(st.mean(lista2))

3.3333333333333335
3.5

In [ ]:
st.variance(lista1)

2.9696969696969697

In [ ]:
st.variance(lista2)

451.72727272727275

In [ ]:
sorted(lista2)

[-50, -2, -1, 0, 3, 3, 4, 4, 5, 6, 30, 40]

In [ ]:
m = st.mean(lista2)
m

3.5

In [ ]:
dp=st.stdev(lista2)
dp

21.253876651737507

In [ ]:
dp2=st.stdev(lista1)
dp2

1.7232808737106582

In [ ]:
m-dp,m+dp

(-17.753876651737507, 24.753876651737507)

In [ ]:
m-2*dp,m+2*dp

(-39.00775330347501, 46.00775330347501)

## Variância e desvio padrão no Pandas

In [19]:
import pandas as pd

df_diabetes=pd.read_excel('/content/drive/MyDrive/CURSOS/Estudos - Data Analitycs/Tic - Análise de dados com paython /Módulo 2/Aula 5/diabetes 1.3.xlsx')
df_diabetes.head()

,pressao arterial,concentraÃ§ao de glicose,insulina,tipo sanguineo,idade,imc,diabetico
0,72.0,148.0,NaN,A,50,33.6,S
1,66.0,85.0,NaN,O,31,26.6,N
2,64.0,183.0,NaN,A,32,23.3,S
3,66.0,89.0,94.0,A,21,28.1,N
4,40.0,137.0,168.0,O,33,43.1,S

In [21]:
df_diabetes[['idade','imc']]

     idade   imc
0       50  33.6
1       31  26.6
2       32  23.3
3       21  28.1
4       33  43.1
..     ...   ...
763     63  32.9
764     27  36.8
765     30  26.2
766     47  30.1
767     23  30.4

[768 rows x 2 columns]

In [22]:
df_diabetes[['idade']].var()

idade    138.303046
dtype: float64

In [23]:
df_diabetes[['imc']].var()

imc    47.955463
dtype: float64

In [24]:
df_diabetes[['idade','imc']].std()

idade    11.760232
imc       6.924988
dtype: float64

In [25]:
df_diabetes[['idade','imc']].mean()

idade    33.240885
imc      32.457464
dtype: float64

A média pode esconder diferenças consideraveis nos conjunto de dados.