<a href="https://colab.research.google.com/github/alra-code/Portifolio_python/blob/main/An%C3%A1lise_de_dados_com_python_modulo_2_(analise_descritiva_dos_dados)_Tic_em_Trilhas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Analise descritiva dos dados

In [4]:
import pandas as pd
df_diabetes3=pd.read_excel('diabetesA6.xlsx')

#Info

In [5]:
df_diabetes3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   pressao arterial          733 non-null    float64
 1   concentraÃ§ao de glicose  763 non-null    float64
 2   insulina                  394 non-null    float64
 3   tipo sanguineo            723 non-null    object
 4   idade                     768 non-null    int64
 5   imc                       757 non-null    float64
 6   diabetico                 768 non-null    object
dtypes: float64(4), int64(1), object(2)
memory usage: 42.1+ KB

#Describe

In [6]:
df_diabetes3.describe()

,pressao arterial,concentraÃ§ao de glicose,insulina,idade,imc
count,733.000000,763.000000,394.000000,768.000000,757.000000
mean,72.405184,121.686763,155.548223,33.240885,32.457464
std,12.382158,30.535641,118.775855,11.760232,6.924988
min,24.000000,44.000000,14.000000,21.000000,18.200000
25%,64.000000,99.000000,76.250000,24.000000,27.500000
50%,72.000000,117.000000,125.000000,29.000000,32.300000
75%,80.000000,141.000000,190.000000,41.000000,36.600000
max,122.000000,199.000000,846.000000,81.000000,67.100000

#Corr

In [9]:
df_diabetes3.corr(numeric_only=True)

,pressao arterial,concentraÃ§ao de glicose,insulina,idade,imc
pressao arterial,1.000000,0.223192,0.098272,0.330107,0.289230
concentraÃ§ao de glicose,0.223192,1.000000,0.581186,0.267136,0.232771
insulina,0.098272,0.581186,1.000000,0.220261,0.228050
idade,0.330107,0.267136,0.220261,1.000000,0.025841
imc,0.289230,0.232771,0.228050,0.025841,1.000000

#Value Counts

In [10]:
df_diabetes3['tipo sanguineo'].value_counts()

tipo sanguineo
A     396
O     228
B      78
AB     21
Name: count, dtype: int64

#Nulos

In [11]:
df_diabetes3.isna()

,pressao arterial,concentraÃ§ao de glicose,insulina,tipo sanguineo,idade,imc,diabetico
0,False,False,True,False,False,False,False
1,False,False,True,False,False,False,False
2,False,False,True,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
763,False,False,False,False,False,False,False
764,False,False,True,False,False,False,False
765,False,False,False,False,False,False,False
766,False,False,True,True,False,False,False
767,False,False,True,False,False,False,False

In [12]:
df_diabetes3.isna().sum()

pressao arterial             35
concentraÃ§ao de glicose      5
insulina                    374
tipo sanguineo               45
idade                         0
imc                          11
diabetico                     0
dtype: int64

In [13]:
df_diabetes3.isna().sum() / len(df_diabetes3)*100

pressao arterial             4.557292
concentraÃ§ao de glicose     0.651042
insulina                    48.697917
tipo sanguineo               5.859375
idade                        0.000000
imc                          1.432292
diabetico                    0.000000
dtype: float64